name: AirysDark-AI - Detector (bootstrap)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch AirysDark-AI tools (ONLY HERE)
        run: |
          set -euxo pipefail
          mkdir -p tools
          BASE_URL="https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools"
          curl -fL "$BASE_URL/AirysDark-AI_detector.py" -o tools/AirysDark-AI_detector.py
          curl -fL "$BASE_URL/AirysDark-AI_android.py"  -o tools/AirysDark-AI_android.py
          curl -fL "$BASE_URL/AirysDark-AI_builder.py"  -o tools/AirysDark-AI_builder.py
          ls -la tools

      - name: Run detector (writes a single PROB workflow)
        run: python3 tools/AirysDark-AI_detector.py

      - name: Stage detector outputs
        id: diff
        run: |
          set -euxo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare PR body
        if: ${{ steps.diff.outputs.changed == 'true' }}
        run: |
          echo "### AirysDark-AI detector results" > pr_body.md
          echo "" >> pr_body.md
          echo '```' >> pr_body.md
          cat tools/airysdark_ai_detector_summary.txt >> pr_body.md
          echo '```' >> pr_body.md
          echo "" >> pr_body.md
          echo "This PR adds:" >> pr_body.md
          echo "- tools/*.py (detector, android handler, builder)" >> pr_body.md
          echo "- .github/workflows/AirysDark-AI_prob.yml (single manual probe workflow)" >> pr_body.md
          echo "" >> pr_body.md
          echo "After merging: run **AirysDark-AI – Probe** and select the target build type." >> pr_body.md

      - name: Pin remote with FG-PAT
        if: ${{ steps.diff.outputs.changed == 'true' }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          REPO_SLUG: ${{ github.repository }}
        run: |
          set -euxo pipefail
          git config --local --name-only --get-regexp '^http\.https://github\.com/\.extraheader$' >/dev/null 2>&1 && \
            git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git remote set-url origin "https://x-access-token:${BOT_TOKEN}@github.com/${REPO_SLUG}.git"
          git config --global url."https://x-access-token:${BOT_TOKEN}@github.com/".insteadOf "https://github.com/"
          git remote -v

      - name: Create PR with PROB workflow
        if: ${{ steps.diff.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ai/airysdark-ai-prob
          commit-message: "chore: add AirysDark-AI_prob.yml + tools (bootstrap)"
          title: "AirysDark-AI: add single PROB workflow + tools"
          body-path: pr_body.md
          labels: automation, ci