name: AirysDark-AI - Detector (bootstrap)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch tools.tar (ONLY here)
        run: |
          set -euxo pipefail
          mkdir -p tools
          # Use the RAW URL for the tarball
          curl -fL "https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools/tools.tar" -o /tmp/tools.tar
          tar -xvf /tmp/tools.tar -C tools
          ls -la tools

      - name: Run detector (generates AirysDark-AI_prob.yml + logs)
        run: |
          set -euxo pipefail
          python3 tools/AirysDark-AI_detector.py

      - name: Stage detector outputs
        id: diff
        run: |
          set -euxo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare PR body (summary + notes)
        if: ${{ steps.diff.outputs.changed == 'true' }}
        run: |
          set -euxo pipefail
          echo "### AirysDark-AI: detector results" > pr_body.md
          echo "" >> pr_body.md
          if [ -f tools/airysdark_ai_detector_summary.txt ]; then
            echo '```' >> pr_body.md
            cat tools/airysdark_ai_detector_summary.txt >> pr_body.md
            echo '```' >> pr_body.md
          else
            echo "_No detector summary found._" >> pr_body.md
          fi
          echo "" >> pr_body.md
          echo "**Next steps:**" >> pr_body.md
          echo "1. Edit \`.github/workflows/AirysDark-AI_prob.yml\` and set **env: TARGET** to the build you want to pursue (e.g. \`android\`, \`linux\`, \`cmake\`)." >> pr_body.md
          echo "2. Merge this PR." >> pr_body.md
          echo "3. Manually run the workflow **AirysDark-AI - Probe** from the Actions tab." >> pr_body.md
          echo "" >> pr_body.md
          echo "_Note: Only this detector workflow fetches tools. The generated probe workflow does not download anything._" >> pr_body.md

      # Configure remote to use a Fine-grained PAT (recommended)
      - name: Configure remote for FG-PAT
        if: ${{ steps.diff.outputs.changed == 'true' }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}   # Fine-grained PAT with repo:contents & PRs
          REPO_SLUG: ${{ github.repository }}
        run: |
          set -euxo pipefail
          git config --local --name-only --get-regexp '^http\.https://github\.com/\.extraheader$' >/dev/null 2>&1 && \
            git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git remote set-url origin "https://x-access-token:${BOT_TOKEN}@github.com/${REPO_SLUG}.git"
          git config --global url."https://x-access-token:${BOT_TOKEN}@github.com/".insteadOf "https://github.com/"
          git remote -v

      - name: Create PR with PROB workflow
        if: ${{ steps.diff.outputs.changed == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ai/airysdark-ai-prob
          commit-message: "chore: add AirysDark-AI_prob.yml + tools (bootstrap)"
          title: "AirysDark-AI: add single PROB workflow + tools"
          body-path: pr_body.md
          labels: automation, ci